controller_list:
  - name: fake_left_robot_arm_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
  - name: fake_right_robot_arm_controller
    joints:
      - rightjoint_s
      - rightjoint_l
      - rightjoint_e
      - rightjoint_u
      - rightjoint_r
      - rightjoint_b
      - rightjoint_t
  - name: fake_dual_robot_arms_controller
    joints:
      - leftjoint_s
      - leftjoint_l
      - leftjoint_e
      - leftjoint_u
      - leftjoint_r
      - leftjoint_b
      - leftjoint_t
      - rightjoint_s
      - rightjoint_l
      - rightjoint_e
      - rightjoint_u
      - rightjoint_r
      - rightjoint_b
      - rightjoint_t